package wfm.components.utils;

/**
 * Взят из hrportal проекта версии 1.8.11632. Комментарии перенеслись из hrportal
 * последний commit https://git.goodt.me/projects/ABC/repos/hrportal/commits/015da5cba3a68dfbcdd7b1f92bb41d3ee7c31ab8 от 08.12.2023
 * <a href="https://git.goodt.me/projects/ABC/repos/hrportal/browse/domain/src/main/java/me/goodt/wfm/domain/entity/security/permissions/PermissionType.java">...</a>
 */
public enum PermissionType {
    /** Оргструктура. Создание. */
    ORGANIZATION_UNIT_CREATE("Оргструктура. Создание."),
    ORGANIZATION_UNIT_TYPE_VIEW("Тип оргструктуры. Просмотр."),
    ORGANIZATION_UNIT_TYPE_EDIT("Тип оргструктуры. Редактирование."),
    ORGANIZATION_UNIT_VIEW("Оргструктура. Просмотр."),
    ORGANIZATION_UNIT_EDIT("Оргструктура. Изменение."),
    ORGANIZATION_UNIT_EVENT_VIEW("События. Просмотр."),
    ORGANIZATION_UNIT_EVENT_EDIT("События. Изменение."),
    ORGANIZATION_UNIT_MANAGER_EDIT("Оргструктура. Назначить руководителем."),
    ORGANIZATION_SHIFT_TEMPLATE("Оргструктура. Шаблоны смен сотрудника."),
    ORGANIZATION_ATTRIBUTES("Оргструктура. Атрибуты подразделения."),
    ORGANIZATION_VACATIONS("Оргструктура. Рекомендации по отпускам."),
    ORGANIZATION_EMPLOYEE_ATTRIBUTES_EDIT("Оргструктура. Редактирование атрибутов сотрудника."),
    ORGANIZATION_EMPLOYEE_ATTRIBUTES_VIEW("Оргструктура. Просмотр атрибутов сотрудника."),
    ORGANIZATION_UNIT_CALCULATION_PARTICIPATION_MANAGEMENT("Оргструктура. Управление участием в расчете."),
    ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PRESENT_AND_FUTURE("Оргструктура. Назначение на позицию в настоящем и будущем."),
    ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PAST("Оргструктура. Назначение на позицию в прошлом."),
    ORGANIZATION_UNIT_POSITION_DISMISS_IN_PRESENT_AND_FUTURE("Оргструктура. Увольнение с позиции в настоящем и будущем."),
    ORGANIZATION_UNIT_POSITION_DISMISS_IN_PAST("Оргструктура. Увольнение с позиции в прошлом."),
    ORGANIZATION_UNIT_SHOW_SERVICE("Оргструктура. Просмотр графика SERVICE."),
    ORGANIZATION_UNIT_NAME_EDIT("Оргструктура. Редактирование ФИО."),
    ORGANIZATION_UNIT_CONTACTS_EDIT("Оргструктура. Редактирование контактов организации."),
    ORGANIZATION_UNIT_TEMPORARY("Оргструктура. Признак временный перевод."),
    ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE("Оргструктура. Изменение даты действия должности в настоящем и будущем."),
    ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PAST("Оргструктура. Изменение даты действия должности в прошлом."),
    EDIT_OUTERID("Оргструктура. Редактирование outerID."),
    ORG_UNIT_SCHEDULE_BLOCK_EDIT("Оргструктура. Редактирование блока графика работы."),
    ORG_UNIT_EXT_POSITION_EDIT("Оргструктура. Расширенное создание назначения."),
    ORG_UNIT_EMPLOYEE_PERSONALISATION("Оргструктура. Отображение перс. данных."),
    ORGANIZATION_UNIT_STAFF_COUNT_VIEW("Оргструктура. Просмотр численности персонала."),
    ORG_EMPLOYEE_CREATE("Оргструктура. Права на создание сотрудника."),
    ORG_EMPLOYEE_EDIT("Оргструктура. Права на редактирование сотрудника."),
    ORG_EMPLOYEE_CONTACT_EDIT("Оргструктура. Редактирование личных контактов."),
    ORG_EMPLOYEE_CONTACT_EDIT_ALL("Оргструктура. Редактирование контактов сотрудников."),
    ORG_SEARCH_BY_ROLE("Оргструктура. Фильтрация по ролям."),
    ORG_OPPORTUNITY_CHANGE_JOBS_TITLE("Оргструктура. Возможность менять название должности."),
    READ_JOB_TITLES("Оргструктура. Чтение должностей."),
    ORG_EDIT_USER_NAME_PARAMETERS("Оргструктура. Изменение логина учетной записи для входа в систему."),
    ORG_EDIT_PASS_PARAMETERS("Оргструктура. Изменение пароля входа в систему."),
    ORG_EDIT_PERSONAL_USER_NAME_PARAMETERS("Оргструктура. Изменение личного логина учетной записи для входа в систему."),
    ORG_EDIT_PERSONAL_PASS_PARAMETERS("Оргструктура. Изменение личного пароля входа в систему."),
    EMPLOYEE_TABLE_RATE("Оргструктура. Ред/просмотр табеля и ставки сотрудника."),
    UNIT_OPERATING_MODE("Оргструктура. Режим работы подразделения."),

    /** Расписание. */
    ROSTER_SHIFT_EDIT_OR_CREATE("Расписание. Права на создание и редактирование смен."),
    ROSTER_SEND_TO_APPROVE("Расписание. Отправка на утверждение."),
    PLAN_TABEL_SHIFT_APPROVE("Расписание. Утверждение смен в плане и табеле."),
    SHIFT_ALLOW_CUSTOM_COMMENT("Расписание. Свободный ввод комментария к смене."),
    SHIFT_MANAGE_COMMENT("Расписание. Редактирование комментария в смене."),
    SHIFT_READ_COMMENT("Расписание. Отображение блока комментариев в карточке смены."),
    CAN_DELETE_SHIFT_BATCH("Расписание. Массовое удаление смен."),
    EDIT_PLAN_PAST("Расписание. Редактирование плана в прошлом."),
    SCHEDULE_AVAILABILITY_TEMPLATE("Расписание. Выгрузка и загрузка доступности через шаблон."),
    ROSTER_UPLOAD_PDF("Расписание. Выгрузка расписания pdf."),
    ROSTER_UPLOAD_XLS("Расписание. Выгрузка расписания xls."),
    RECALCULATION_OF_SHIFTS("Расписание. Расчет/Перерасчет смен."),
    SCHEDULE_VIEW("Расписание. Просмотр."),
    SCHEDULE_EDIT("Расписание. Изменение."),
    SCHEDULE_OVERTIME_WORK("Расписание. Редактирование сверхурочной работы."),
    SCHEDULE_DUTY("Расписание. Редактирование дежурств."),
    SCHEDULE_EMPLOYEE_ZONE_LINK_EDIT("Расписание. Привязка сотрудника к залу."),
    SCHEDULE_EVENTS("Расписание. События просмотр/управление."),
    SCHEDULE_DAY_COMMENTS("Расписание. Комментарии к дням."),
    SCHEDULE_SHIFT_TIME("Расписание. Смещение режима."),
    SCHEDULE_VERSION_COMMENTS("Расписание. Комментарии к версиям расчета."),
    SCHEDULE_PERSONAL("Расписание. Личное расписание."),
    SCHEDULE_EDIT_WORKED("Расписание. Редактирование табеля без ограничений."),
    SCHEDULE_EDIT_PLAN("Расписание. Редактирование плана без ограничений."),
    NORMATIVE_SHOW("Расписание. Просмотр месячных нормативов."),
    NORMATIVE_EDIT("Расписание. Редактирование месячных нормативов."),
    SET_SHIFT_ADD_WORK("Расписание. Редактирование доп работ в смене."),
    BUSINESS_TRIP_LOGISTICS_READ("Расписание. Командировка логистики (просмотр)."),
    BUSINESS_TRIP_LOGISTICS_EDIT("Расписание. Командировка логистики (изменение)."),
    SCHEDULE_CREATE_RV_SV("Расписание. Создание РВ/СВ."),
    SCHEDULE_CUSTOM_INDICATORS("Расписание. Настройка индикаторов."),
    SCHEDULE_CALCULATION_SHIFTS("Расписание. Расчет смен."),
    SCHEDULE_PUBLISH_SHIFTS("Расписание. Публикация смен."),
    SCHEDULE_EXPORT("Расписание. Выгрузка расписания dbf."),
    SHIFT_WIZARD("Расписание. Мастер планирования."),
    SCHEDULE_MANAGE_REQUESTS_CREATE("Расписание. Создание неподтвержденных запросов (себе)."),
    SCHEDULE_MANAGE_REQUESTS_APPROVE("Расписание. Управление пожеланиями (подтверждение, отклонение)."),
    SCHEDULE_MANAGE_REQUESTS("Расписание. Управление пожеланиями (создание, редактирование, удаление)."),
    CONSTRAINT_VIOLATION_SETTINGS_EDIT("Расписание. Установки конфликтов редактирование."),
    SCHEDULE_LUNCH_EDIT("Расписание. Редактирование длины обеда."),
    SCHEDULE_GRAPH_COMPARSION_MODE("Расписание. Режим сравнения графиков."),
    SCHEDULE_TIMESHEET_COMPARSION_MODE("Расписание. Режим сравнения табеля."),
    SCHEDULE_REPORT_CARD("Расписание. Табель учета."),
    CREATING_SCHEDULE_REQUESTS_USING_PERIODICITY_METHOD("Расписание. Создание запросов расписания методом периодичности."),
    EDIT_INTEGRATION_SHIFTS("Расписание. Редактирование интеграционных смен."),
    EDIT_INTEGRATION_SCHEDULE_REQUESTS("Расписание. Редактирование интеграционных запросов расписания."),
    SCHEDULE_PUBLISH_WITH_OVERTIME_LIMIT_VIOLATION("Расписание. Публикация с превышением лимитов."),

    /** Аналитика. */
    ANALYTIC_VIEW("Аналитика. Просмотр."),
    ANALYTIC_EDIT("Аналитика. Изменение."),
    ANALYTIC_CALCULATE_FORECAST("Аналитика. Расчет прогноза."),
    ANALYTIC_PUBLISH_KPI("Аналитика. Публикация kpi."),
    ANALYTIC_CALCULATE_FTE("Аналитика. Расчет FTE."),
    ANALYTIC_PUBLISH_FTE("Аналитика. Публикация FTE."),

    /** Отчеты. */
    REPORT_VIEW("Отчеты. Просмотр."),
    REPORTS_CONSTRUCTOR("Отчеты. Конструктор отчетов."),
    REPORT_PRINT_FORMS("Отчеты. Печатные формы."),
    REPORT_SHIFTS("Отчеты. Смены."),
    REPORT_X5_FTE_STATS("Отчеты. Отчет по покрытию РЗ и утилизации."),
    REPORT_COUNT_BY_ROSTER("Отчеты. Численность по графикам."),
    REPORT_ROSTER_PUBLISH_STATE("Отчеты. Статус публикации графиков."),
    REPORT_HISTORY_DATA_QUALITY("Отчеты. Качество исторических данных."),
    REPORT_DAY_OFF_QUOTES("Отчеты. Квоты выходных дней."),
    REPORT_ANALYSE_AVERAGE_CONVERSION("Отчеты. Анализ средней конверсии."),
    REPORT_PLAN_FACT_CONVERSION("Отчеты. Плановая и фактическая конверсии."),
    REPORT_STAFF_COUNT("Отчеты. Численность персонала."),
    REPORT_TARGET_STAFF_COUNT("Отчеты. Целевая численность персонала."),
    REPORT_PARAMETERS_VALUES("Отчеты. Значения используемых параметров."),
    REPORT_TIME_SHEET("Отчеты. Табель учета рабочего времен."),
    REPORT_LOAD("Отчеты. Экспорт отчета."),
    REPORT_FACT_WORK_EMPLOYEE("Отчеты. Факт работы сотрудника."),
    REPORT_ATTENDANCE("Отчеты. Посещаемость."),
    REPORT_PLAN_FACT_CORRECT("Отчеты. План, факт, скорректированный факт."),
    REPORT_PLAN_TABEL("Отчеты. Печать планового табеля."),
    REPORT_DISCIPLINE("Отчеты. По дисциплине."),
    REPORT_LABOR_DISCIPLINE("Отчеты. Трудовая дисциплина (РА)."),
    REPORT_DESCRIPTORS("Отчеты. Отчет по дескрипторам"),
    REPORT_PUBLISHING_ROSTERS("Отчеты. Отчет о публикации графиков."),
    REPORT_SUM_BALANCE_PROCESSING("Отчеты. Накопленный баланс переработок."),
    REPORT_OPS_DONORS_ACCEPTORS("Отчеты. Отчет ОПС-доноры и ОПС-акцепторы."),
    REPORT_EMPLOYEES_ATTRIBUTES("Отчеты. Выгрузка атрибутов сотрудников."),
    REPORT_OUTSTAFF("Отчеты. Смены внешних сотрудников."),
    REPORT_DAILY_FACT("Отчеты. Фактически отработанные часы (подневной факт)."),
    REPORT_DAILY_WORK_HOURS("Отчеты. Отработанное время."),
    REPORT_WORK_TIME_FOR_POSITION_TYPES("Отчеты. Отчет по фонду рабочего времени."),
    REPORT_BIO_STATUS("Отчеты. Отчет по бирже смен."),
    REPORT_TARGET_TABEL("Отчеты. Целевой табель."),
    REPORT_ACCURACY_CALCULATED_TIME_BALANCE("Отчеты. Точность рассчитанного баланса часов."),
    REPORT_TECHNICAL_TABLE("Отчеты. Техническая выгрузка табеля."),
    REPORT_ACTUAL_COMPLETENESS_FOR_GIVEN_DATE("Отчеты. Отчет по фактической комплектности на заданную дату."),
    REPORT_ACTUAL_COMPLETENESS("Отчеты. Отчет по фактической комплектности."),
    REPORT_USER_LOGINS("Отчеты. Выгрузка входов пользователей."),
    REPORT_DISCIPLINE_BREAKING("Отчеты. Нарушение дисциплины."),
    REPORT_USERS_TIME_IN_SYSTEM("Отчеты. Время, проведенное пользователями в системе."),
    REPORT_TARGET_STAFFING("Отчеты. Целевая штатная численность."),
    REPORT_KONTRAGENTS("Отчеты. Оценка сотрудников контрагентов."),
    REPORT_ORG_UNIT_EVENTS("Отчеты. События по организации."),
    REPORT_POSITION_GROUPS_BF("Отчеты. Отчет по группам должностей БФ."),
    REPORT_FORECAST_FACT_DIFFERENCE("Отчеты. Расхождение фактических и прогнозных значений."),
    ROSTER_VERSION_COMPARISON_REPORT("Отчеты. Отчет по корректировкам смен."),
    REPORT_WORKED_HOURS_BY_DATE("Отчеты. Отработанное время по дням."),
    REPORT_TABEL_CONFLICTS("Отчеты. Отчет по корректности табеля."),
    REPORT_SHIFT_LOGS("Отчеты. Логи смен."),
    REPORT_USER_ACCOUNT("Отчеты. Отчет по учетным записям."),
    REPORT_SVP_ADJUSTMENT("Отчеты. Отчет по корректировкам СВП."),
    REPORT_WORK_TIME("Отчеты. Об отработанном времени."),
    REPORT_USAGE_OF_EXCHANGE_SHIFTS("Отчет норматива по использованию смен подработки"),
    REPORT_CLOSING_OF_EXCHANGE_SHIFTS("Отчет по закрытию заявок ВП"),
    REPORT_SVP_SALARY("Отчеты. Расчёт ЗП по СВП."),
    REPORT_OUTSOURCE_SALARY("Отчеты. Расчёт ЗП по аутсорсу."),
    REPORT_KPI_PLAN_FACT("Отчеты. Сопоставление прогноза и факта."),
    REPORT_OUTSOURCE_PLAN_FACT("Отчеты. Отчет об отработанном времени аутсорсинга."),
    REPORT_EFES_TIMESHEET("Отчёты. Табель учета раб. времени Efes"),
    REPORT_EFES_COSTCENTER("Отчёты. Отчёт по МВЗ Efes"),
    REPORT_WORK_TIME_BF("Отчеты. Отчет Табель БФ"),
    REPORT_EFES_PLAN_FACT_HOURS("Отчеты. Отчет плановых и фактических часов"),
    JASPER_REPORTS_SHIFTS_PLAN("Отчёты. Плановый график."),
    JASPER_REPORTS_SHIFTS_PLAN_WITHOUT_LUNCH("Отчёты. Плановый график (без обедов)."),
    REPORT_ON_OPS_WITH_COMPARISON_NORM("Отчеты. Отчет по ОПС с сопоставлением нормы часов по произв.календарю и нормой по режиму работы"),
    REPORT_LIMITS("Отчеты. Лимиты."),
    REPORT_AUTO_OPENED_PERIOD("Отчеты. Отчет по списку Исключений правил табеля."),
    REPORT_MOBILE_APPLICATION_STATISTICS("Отчеты. Отчет по статистике мобильного приложения"),
    //Отчеты. Почта
    REPORT_SCHEDULE_CHANGES_RUSSIAN_POST("Отчёты. По изменению графиков работы."),
    REPORT_OPERBLOCK_RUSSIAN_POST("Отчёты. Еженедельный для оперблока."),
    REPORT_COMPARE_VERSION_COUNT_OF_STAFF("Отчёты. Сравнение версий штатной численности"),
    REPORT_CORRECTED_SHIFTS_RUSSIAN_POST("Отчёты. По ручным корректировкам данных фактического посещения"),
    REPORT_TIMESHEET_RUSSIAN_POST("Отчёты. По табелю"),
    REPORT_SHORTAGE_AND_EXCEEDING("Отчёты. По переработкам и недоработкам"),
    REPORT_ACTUAL_VACATION_RUSSIAN_POST("Отчеты. Отчет Фактических отпусков"),
    REPORT_ACTUAL_COMPLETENESS_RUSSIAN_POST("Отчеты. Отчет по фактической комплектности"),
    REPORT_SHIFT_ADD_WORK_LOG("Отчеты. Отчёт по добавлению, удалению, редактированию доп.работ"),
    REPORT_PUBLISHED_WITH_OVERTIME_DEVIATIONS("Отчеты. Отчет о выполнении публикации с превышением годовой переработки 120ч"),

    /** Задачи. */
    TASKS_VIEW("Задачи. Просмотр."),
    TASKS_EDIT("Задачи. Изменение."),
    TASKS_CHANGE_AUTHOR_STATE("Задачи. Изменение статуса автор задачи."),
    TASKS_CHANGE_EXECUTOR_STATE("Задачи. Изменение статуса исполнителя."),

    /** Управление ролями. */
    ROLES_VIEW("Управление ролями. Просмотр."),
    ROLES_EDIT("Управление ролями. Изменение."),
    ROLES_DISTRIBUTION_VIEW("Управление ролями. Распределение ролей. Просмотр."),
    ROLES_DISTRIBUTION_EDIT("Управление ролями. Распределение ролей. Изменение."),

    /** Массовый расчет. */
    BULK_CALCULATION_VIEW("Массовый расчет. Просмотр."),
    BULK_CALCULATION_FORECAST("Массовый расчет. Рассчитать прогноз."),
    BULK_CALCULATION_FTE("Массовый расчет. Рассчитать FTE."),
    BULK_CALCULATION_SHIFTS("Массовый расчет. Рассчитать смены."),
    BULK_CALCULATION_PLAN_COUNT("Массовый расчет. Рассчитать плановую численность."),

    /** Математические параметры. */
    MATH_PARAMETERS_VIEW("Математические параметры. Просмотр."),
    MATH_PARAMETERS_SYSTEM_EDIT("Математические параметры. Редактирование списка."),
    MATH_PARAMETERS_EDIT("Математические параметры. Изменение."),
    MATH_PARAMETERS_HISTORY_VIEW("Математические параметры. Просмотр истории."),

    /** Рабочий стол. */
    DESKTOP_SUMMARY("Рабочий стол. Виджет \"Сводные данные\"."),
    DESKTOP_NORMATIVES("Рабочий стол. Виджет \"Нормы времени\"."),
    DESKTOP_LOYALTY("Рабочий стол. Виджет \"Лояльность\"."),
    DESKTOP_EMPLOYEE_TIME("Рабочий стол. Виджет \"Время сотрудников\"."),
    DESKTOP_SERVICE_LEVEL("Рабочий стол. Виджет \"Уровень сервиса\"."),
    DESKTOP_ACCURACY_KPI_FORECAST("Рабочий стол. Виджет \"Точность прогноза kpi\"."),

    /** Разное. */
    OTHER_VIEW_PROFILE("Разное. Просмотр профиля."),
    OTHER_VIEW_HELP("Разное. Просмотр справки."),
    OTHER_WELCOME_PAGE("Разное. Блок добро пожаловать."),
    OTHER_VIEW_SUPPORT("Разное. Служба поддержки."),
    OTHER_MENU_KPI("Разное. Меню бизнес-драйвера."),
    OTHER_APPROVE_PST("Разное. Согласование ПШЧ."),
    OTHER_SEND_ON_APPROVE_PST("Разное. Отправка на согласование ПШЧ."),
    OTHER_MENU_LOAD_KPI("Разное. Меню загрузки файлов бизнес-драйвера."),
    OTHER_MENU_TYPE_EVENTS("Разное. Меню Типы событий."),
    OTHER_MENU_RESULT_CALCULATE("Разное. Меню результат расчета рабочей нагрузки."),
    OTHER_MENU_NORMATIVE("Разное. Меню нормативы."),
    OTHER_MENU_LOAD_TABLE("Разное. Выгрузка табеля фактического посещения."),
    ACCESS_TO_PERSONAL_ACCOUNT_OF_COUNTERPARTY("Разное. Доступ в личный кабинет контрагента (ЛК КА)."),
    OTHER_VIEW_CALCULATED_NUMBER_OF_STAFF("Разное. Просмотр расчетной численности персонала."),
    OTHER_UPLOAD_START_DATA_DATA_IMPORT("Разное. Загрузка начальных данных. Импорт данных."),
    OTHER_UPLOAD_START_DATA_TECHNICAL_WORK("Разное. Загрузка начальных данных. Информирование о технических работах."),
    OTHER_UPLOAD_DATA_HELP("Разное. Загрузить инструкцию для расчетов в раздел \"Справка\""),
    OTHER_UPLOAD_FILE("Разное. Загрузить файл в раздел \"Справка\""),
    OTHER_PRODUCTION_CALENDAR_VIEW("Разное. Производственные календари. Чтение"),
    OTHER_PRODUCTION_CALENDAR_EDIT("Разное. Производственные календари. Редактирование"),

    /** Уведомления. */
    NOTIFY_VIEW("Уведомления. Отображение блока уведомлений в меню"),
    NOTIFY_APPROVE_REQUEST("Уведомления. Об утверждении запроса."),
    NOTIFY_REJECT_REQUEST("Уведомления. Об отклонении запроса."),
    NOTIFY_APPROVED_REQUEST("Уведомления. Запрос утвержден."),
    NOTIFY_MANAGER("Уведомления. Уведомления менеджера."),
    NOTIFY_FTE_CALC("Уведомления. О расчете FTE."),
    ACCEPT_NIGHT_SHIFT("Уведомления. О согласовании 3й ночной смены."),
    NOTIFY_COUNT_UNREAD("Уведомления. О количестве не прочитанных."),
    NOTIFY_SHIFT_PLAN_EDIT("Уведомления. О ред. плановой смены в закрытом периоде."),
    NOTIFY_DESCRIPTOR_NEEDED("Уведомления. О расчете дескрипторов"),
    NOTIFY_ON_SCHEDULE_PUBLISH_SHIFTS("Уведомления. О публикации графика."),
    NOTIFY_ON_EMPLOYEE_SCHEDULE_CHANGE("Уведомления. Об изменении графика."),

    /** Внешние ссылки. */
    EXTERNAL_SUPPORT("Внешние ссылки. Служба поддержки."),
    EXTERNAL_AUTH_GAMING("Внешние ссылки. Ссылка для авторизации в гейминге."),
    EXTERNAL_CALC_COUNT("Внешние ссылки. Ссылка на расчет штатной численности."),
    EXTERNAL_CHECK_IN("Внешние ссылки. Ссылка отметиться."),
    EXTERNAL_TABLE_LINK("Внешние ссылки. Ссылка на страницу табеле в основном меню."),
    EXTERNAL_MANAGER_PANE("Внешние ссылки. Ссылка на страницу панели руководителя в основном меню."),

    /** Системные списки. */
    SYS_LISTS_MENU("Системные списки. Меню."),
    SYS_LIST_ALIASES_READ("Системные списки. Типы запросов расписания чтение."),
    SYS_LIST_ALIASES_EDIT("Системные списки. Типы запросов расписания редактирование."),
    SYS_LIST_ALIASES_EDIT_POINT("Системные списки. Типы запросов расписания редактирование (точечное)."),
    SYS_LIST_ORG_TYPES_READ("Системные списки. Типы подразделений чтение."),
    SYS_LIST_ORG_TYPES_EDIT("Системные списки. Типы подразделений редактирование."),
    SYS_LIST_HIRING_REASON_READ("Системные списки. Причины привлечения сотрудника чтение."),
    SYS_LIST_HIRING_REASON_EDIT("Системные списки. Причины привлечения сотрудника редактирование."),
    SYS_LIST_ADD_WORK_RULES_READ("Системные списки. Правила доп. работ. Чтение."),
    SYS_LIST_ADD_WORK_RULES_EDIT("Системные списки. Правила доп. работ. Редактирование."),
    SYS_LIST_EXCHANGE_RULES_READ("Системные списки. Правила биржи смен чтение."),
    SYS_LIST_EXCHANGE_RULES_EDIT("Системные списки. Правила биржи смен редактирование."),
    SYS_LIST_TABLE_RULES_READ("Системные списки. Правила табеля чтение."),
    SYS_LIST_TABLE_RULES_EDIT("Системные списки. Правила табеля редактирование."),
    SYS_LIST_CONFLICT_RULES_READ("Системные списки. Установка конфликтов чтение."),
    SYS_LIST_CONFLICT_RULES_EDIT("Системные списки. Установка конфликтов редактирование."),
    SYS_LIST_LIMITS_READ("Системные списки. Лимиты. Чтение."),
    SYS_LIST_LIMITS_EDIT("Системные списки. Лимиты. Редактирование."),
    SYS_LIST_BREAKS_RULES_READ("Системные списки. Перерывы. Чтение."),
    SYS_LIST_BREAKS_RULES_EDIT("Системные списки. Перерывы. Редактирование."),
    SYS_LIST_AUTO_PLAN_RULES_READ("Системные списки. Автопостроение плана. Чтение."),
    SYS_LIST_AUTO_PLAN_RULES_EDIT("Системные списки. Автопостроение плана. Редактирование."),
    SYS_LIST_TIMESHEET_EDIT_PERMISSION_READ("Системные списки. Разрешения на редактирование табеля. Чтение."),
    SYS_LIST_TIMESHEET_EDIT_PERMISSION_EDIT("Системные списки. Разрешения на редактирование табеля. Редактирование."),
    SYS_LIST_TIMESHEET_EDIT_PERMISSION_EDIT_TIMESHEET("Системные списки. Разрешения на редактирование табеля. Создание и удаление разрешений для смен табеля."),
    SYS_LIST_TIMESHEET_EDIT_PERMISSION_EDIT_EXCHANGE("Системные списки. Разрешения на редактирование табеля. Создание и удаление разрешений для смен биржи."),
    SYS_LIST_JOB_GROUPS_READ("Системные списки. Группы должностей. Чтение."),
    SYS_LIST_JOB_GROUPS_EDIT("Системные списки. Группы должностей. Редактирование."),
    SYS_LIST_SCHEDULE_REQUEST_ALIAS_RULES_READ("Системные списки. Правила для запроса расписания. Чтение."),
    SYS_LIST_SCHEDULE_REQUEST_ALIAS_RULES_EDIT("Системные списки. Правила для запроса расписания. Редактирование."),
    SYS_LIST_FUNCTION_DIRECTORY_READ("Системные списки. Справочник функций. Чтение."),
    SYS_LIST_FUNCTION_DIRECTORY_EDIT("Системные списки. Справочник функций. Редактирование."),
    SYS_LIST_LOGISTIC_EXCHANGE_READ("Системные списки. Справочник по должностям биржи логистики. Чтение."),
    SYS_LIST_LOGISTIC_EXCHANGE_EDIT("Системные списки. Справочник по должностям биржи логистики. Редактирование."),
    SYS_LIST_ROSTER_LIMIT_KPI_READ("Системные списки. Настройки отображения рек. штата. Чтение."),
    SYS_LIST_ROSTER_LIMIT_KPI_EDIT("Системные списки. Настройки отображения рек. штата. Редактирование."),
    SYS_LIST_MG_KPI_VISIBILITY_READ("Системные списки. Отображение рек. штата. Чтение."),
    SYS_LIST_MG_KPI_VISIBILITY_EDIT("Системные списки. Отображение рек. штата. Редактирование."),
    SYS_LIST_NORM_BY_TYPE_READ("Системные списки. Настройки расчета нормативов по БН. Чтение."),
    SYS_LIST_NORM_BY_TYPE_EDIT("Системные списки. Настройки расчета нормативов по БН. Редактирование."),
    SYS_LIST_CONFLICT_TEMPLATE_READ("Системные списки. Шаблоны конфликтов. Чтение."),
    SYS_LIST_CONFLICT_TEMPLATE_EDIT("Системные списки. Шаблоны конфликтов. Редактирование."),
    SYS_LIST_EMPLOYEE_POSITION_POPUP_PARAMS_EDIT("Системные списки. Редактирование списка pop-up параметров сотрудника."),
    SYS_LIST_SETTING_DISPLAY_CONFLICTS_READ("Системные списки. Настройка отображения конфликтов, чтение"),
    SYS_LIST_SETTING_DISPLAY_CONFLICTS_EDIT("Системные списки. Настройка отображения конфликтов, редактирование"),
    SYS_LIST_ROSTER_SHIFT_TEMPLATE_READ("Системные списки. Графики смен. Чтение"),
    SYS_LIST_ROSTER_SHIFT_TEMPLATE_EDIT("Системные списки. Графики смен. Редактирование"),

    /** Системный список типы доп работ */
    SYS_LIST_ADD_WORK_READ("Типы доп. работ. Просмотр."),
    SYS_LIST_ADD_WORK_EDIT("Типы доп. работ. Изменение."),
    SYS_LIST_ADD_WORK_TITLE_READ("Типы доп работ. Поле \"Название\". Просмотр."),
    SYS_LIST_ADD_WORK_TITLE_EDIT("Типы доп работ. Поле \"Название\". Изменение."),
    SYS_LIST_ADD_WORK_OUTERID_READ("Типы доп работ. Поле \"OuterId\". Просмотр."),
    SYS_LIST_ADD_WORK_OUTERID_EDIT("Типы доп работ. Поле \"OuterId\". Создание."),
    SYS_LIST_ADD_WORK_DISABLED_READ("Типы доп работ. Поле \"Отключен\". Просмотр."),
    SYS_LIST_ADD_WORK_DISABLED_EDIT("Типы доп работ. Поле \"Отключен\". Изменение."),
    SYS_LIST_ADD_WORK_HAS_STATUSES_READ("Типы доп работ. Поле \"Использует статусы\". Просмотр."),
    SYS_LIST_ADD_WORK_HAS_STATUSES_EDIT("Типы доп работ. Поле \"Использует статусы\". Изменение."),
    SYS_LIST_ADD_WORK_STATUSES_READ("Типы доп работ. Поле \"Статусы\". Просмотр."),
    SYS_LIST_ADD_WORK_STATUSES_EDIT("Типы доп работ. Поле \"Статусы\". Изменение."),

    /** Системные действия. */
    SYS_ACTIONS_MENU("Системные действия. Меню."),
    SYS_ACTION_PROCESS_BIO_RECORDS_BY_DAYS("Системные действия. Пересчёт смен из УРВ."),
    SYS_ACTION_RECORD_DETACH("Системные действия. Снятие статуса отметки."),
    SYS_ACTION_BIO_CREATE_RECORDS_FROM_PLAN("Системные действия. Создать отметки по плановым сменам."),
    SYS_ACTION_CREATE_EMPTY_PLANNED_ROSTER("Системные действия. Создать пустой ростер."),
    SYS_ACTION_RECALCULATION_NORMS_FOR_SELECTED_PERIOD("Системные действия. Пересчет норм за выбранный период."),
    SYS_ACTION_TRANSACTION_TO_MONTH_NORM_ACCOUNTING("Системные действия. Переход к месячному виду суммированного учета."),

    POSITION_TYPES_VIEW("Типы позиций. Просмотр."),
    POSITION_TYPES_EDIT("Типы позиций. Изменение."),
    POSITION_CATEGORIES_VIEW("Категории позиций. Просмотр."),
    POSITION_CATEGORIES_EDIT("Категории позиций. Изменение."),
    POSITION_GROUPS_VIEW("Функциональные роли. Просмотр."),
    POSITION_GROUPS_EDIT("Функциональные роли. Изменение."),
    INTEGRATION_LOG_VIEW("Лог интеграции. Просмотр."),

    /** Биржа */
    OTHER_GENERAL_EXCHANGE("Биржа. Общая биржа смен."),
    CREATE_SHIFT_EXCHANGE("Биржа. Создание и копирование свободных смен на бирже."),
    SCHEDULE_SHIFT_EXCHANGE_EDIT_WORKED("Биржа. Действия со сменами биржи без ограничений."),
    EDIT_EMPLOYEE_TAGS("Биржа. Редактирование тегов сотрудника."),
    EDIT_SELF_TAGS("Биржа. Редактирование своих тегов."),
    EDIT_ORG_UNIT_TAGS("Биржа. Редактирование тегов подразделения."),
    SCHEDULE_EXCHANGE_CONFIRM("Биржа. Утверждение биржи смен."),
    EDIT_ASSIGNED_EXCHANGE_SHIFT("Биржа. Редактирование назначенных смен с биржи."),
    DELETE_ASSIGNED_EXCHANGE_SHIFT("Биржа. Удаление назначенных смен на бирже."),
    ROSTER_EDIT_EXCHANGE("Биржа. Редактирование и удаление свободных смен на бирже."),
    HIRING_REASON_EDIT("Биржа. Поле Причина привлечения сотрудника."),
    SHIFT_EXCHANGE_FOR_SELF("Биржа. Биржа смен (отдать/запросить) смены для себя."),
    SCHEDULE_REQUEST_SHIFT_EXCHANGE("Биржа. Биржа смен (отдать/запросить)."),
    SHIFT_EXTERNAL_USER("Биржа. Смена для внешнего сотрудника."),
    OUTSTAFF_AND_EXTERNAL("Биржа. Аутстафф или Внешний совместитель."),
    ROSTER_EXCHANGE_RECALCULATE_SHIFTS("Биржа. Пересчет смен на бирже."),
    SHIFT_EXCHANGE_SET_IN_PAST("Биржа. Редактирование и назначение смен с биржи в табель."),
    ;

    private final String title;

    PermissionType(String title) {
        this.title = title;
    }

    public String getValue() {
        return this.name();
    }

    public String getTitle() {
        return title;
    }

}