package wfm.components.utils;

import wfm.models.MathParameter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import static wfm.components.utils.PermissionType.*;

/**
 * Енам наполнен по https://wiki.goodt.me/pages/viewpage.action?pageId=197461010
 */
public enum Role {
    ADMIN(Arrays.asList(PermissionType.values()), "0_superuser", Arrays.asList(RolesSections.values())),

    ADMIN_TT(Arrays.asList(ORG_UNIT_EMPLOYEE_PERSONALISATION, ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_CALCULATION_PARTICIPATION_MANAGEMENT,
            ORG_SEARCH_BY_ROLE, READ_JOB_TITLES, EDIT_EMPLOYEE_TAGS, EDIT_ORG_UNIT_TAGS, EDIT_SELF_TAGS, SCHEDULE_CUSTOM_INDICATORS,
            HIRING_REASON_EDIT, SHIFT_ALLOW_CUSTOM_COMMENT, SET_SHIFT_ADD_WORK, SHIFT_WIZARD, SCHEDULE_MANAGE_REQUESTS, SCHEDULE_VIEW,
            SCHEDULE_EDIT, SCHEDULE_PUBLISH_SHIFTS, SCHEDULE_DAY_COMMENTS, SCHEDULE_VERSION_COMMENTS, SCHEDULE_MANAGE_REQUESTS_CREATE,
            SCHEDULE_EXPORT, CONSTRAINT_VIOLATION_SETTINGS_EDIT, REPORT_VIEW, REPORT_PLAN_TABEL, REPORT_TARGET_TABEL, REPORT_WORK_TIME,
            REPORT_POSITION_GROUPS_BF, REPORT_TABEL_CONFLICTS, REPORT_SVP_ADJUSTMENT, REPORT_WORK_TIME_BF, ROLES_VIEW, ROLES_DISTRIBUTION_VIEW,
            ROLES_DISTRIBUTION_EDIT, POSITION_TYPES_VIEW, POSITION_TYPES_EDIT, POSITION_CATEGORIES_VIEW, POSITION_CATEGORIES_EDIT,
            OTHER_VIEW_PROFILE, OTHER_VIEW_HELP, OTHER_GENERAL_EXCHANGE, POSITION_GROUPS_VIEW, SYS_LISTS_MENU, SYS_LIST_ALIASES_READ,
            SYS_LIST_ALIASES_EDIT, SYS_LIST_HIRING_REASON_READ, SYS_LIST_HIRING_REASON_EDIT, SYS_LIST_EXCHANGE_RULES_READ,
            SYS_LIST_EXCHANGE_RULES_EDIT, SYS_LIST_TABLE_RULES_READ, SYS_LIST_TABLE_RULES_EDIT, SYS_LIST_CONFLICT_RULES_READ,
            SYS_LIST_CONFLICT_RULES_EDIT, SYS_LIST_LIMITS_READ, SYS_LIST_LIMITS_EDIT, ROSTER_EDIT_EXCHANGE, SHIFT_EXTERNAL_USER,
            CREATE_SHIFT_EXCHANGE, SCHEDULE_EDIT_WORKED, SCHEDULE_EDIT_PLAN), "Администратор ТТ", Arrays.asList(RolesSections.values())),

    FIRST(Arrays.asList(ORG_UNIT_EMPLOYEE_PERSONALISATION, ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT,
            ORGANIZATION_UNIT_CALCULATION_PARTICIPATION_MANAGEMENT, ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PAST, ORGANIZATION_UNIT_POSITION_DISMISS_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_POSITION_DISMISS_IN_PAST, ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PAST, ORG_UNIT_SCHEDULE_BLOCK_EDIT,
            SYS_LIST_ORG_TYPES_READ, SYS_LIST_ORG_TYPES_EDIT,
            SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_CALCULATION_SHIFTS, SCHEDULE_PUBLISH_SHIFTS, SCHEDULE_EXPORT, SCHEDULE_MANAGE_REQUESTS,
            SCHEDULE_PERSONAL, SCHEDULE_MANAGE_REQUESTS_CREATE, SCHEDULE_OVERTIME_WORK, SCHEDULE_DUTY,
            ANALYTIC_VIEW, ANALYTIC_EDIT, ANALYTIC_CALCULATE_FORECAST, ANALYTIC_PUBLISH_KPI, ANALYTIC_CALCULATE_FTE, ANALYTIC_PUBLISH_FTE,
            REPORT_VIEW, REPORT_PRINT_FORMS, REPORT_SHIFTS, REPORT_COUNT_BY_ROSTER, REPORT_ROSTER_PUBLISH_STATE, REPORT_HISTORY_DATA_QUALITY,
            REPORT_DAY_OFF_QUOTES, REPORT_ANALYSE_AVERAGE_CONVERSION, REPORT_PLAN_FACT_CONVERSION, REPORT_STAFF_COUNT, REPORT_TIME_SHEET,
            REPORT_TARGET_STAFF_COUNT, REPORT_PARAMETERS_VALUES,
            BULK_CALCULATION_VIEW, BULK_CALCULATION_FORECAST, BULK_CALCULATION_FTE, BULK_CALCULATION_SHIFTS, BULK_CALCULATION_PLAN_COUNT,
            MATH_PARAMETERS_VIEW, MATH_PARAMETERS_EDIT, MATH_PARAMETERS_SYSTEM_EDIT,
            POSITION_TYPES_VIEW, POSITION_TYPES_EDIT,
            POSITION_CATEGORIES_VIEW, POSITION_CATEGORIES_EDIT,
            ROLES_VIEW, ROLES_EDIT,
            UNIT_OPERATING_MODE,
            POSITION_GROUPS_VIEW, POSITION_GROUPS_EDIT,
            DESKTOP_SUMMARY, DESKTOP_NORMATIVES, DESKTOP_LOYALTY, DESKTOP_EMPLOYEE_TIME, DESKTOP_ACCURACY_KPI_FORECAST,
            OTHER_VIEW_PROFILE, ROSTER_UPLOAD_XLS), "1_generated", Arrays.asList(RolesSections.values())),

    SECOND(Collections.singletonList(UNIT_OPERATING_MODE), "2_generated", new ArrayList<>()),

    THIRD(Arrays.asList(SCHEDULE_VIEW, SCHEDULE_EDIT,
            ORGANIZATION_UNIT_VIEW, SCHEDULE_VIEW, ANALYTIC_VIEW,
            ORG_UNIT_EMPLOYEE_PERSONALISATION,
            REPORT_VIEW, REPORT_PRINT_FORMS,
            UNIT_OPERATING_MODE,
            BULK_CALCULATION_VIEW, BULK_CALCULATION_FORECAST,
            MATH_PARAMETERS_VIEW, POSITION_TYPES_VIEW, POSITION_CATEGORIES_VIEW, ROLES_VIEW, POSITION_GROUPS_VIEW, DESKTOP_SUMMARY),
            "3_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD, RolesSections.BATCH_CALCULATION,
            RolesSections.REPORTS, RolesSections.ANALYTICS, RolesSections.FUNCTIONAL_ROLES, RolesSections.POSITION_TYPES)),

    FOURTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_CALCULATION_PARTICIPATION_MANAGEMENT, ORG_UNIT_EMPLOYEE_PERSONALISATION,
            SYS_LIST_ORG_TYPES_READ, SYS_LIST_ORG_TYPES_EDIT,
            UNIT_OPERATING_MODE,
            SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_CALCULATION_SHIFTS, SCHEDULE_DUTY,
            ANALYTIC_VIEW, ANALYTIC_EDIT, ANALYTIC_CALCULATE_FORECAST,
            REPORT_VIEW, REPORT_SHIFTS,
            BULK_CALCULATION_VIEW, BULK_CALCULATION_FTE,
            DESKTOP_NORMATIVES,
            PermissionType.POSITION_GROUPS_VIEW), "4_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD,
            RolesSections.BATCH_CALCULATION, RolesSections.REPORTS, RolesSections.ANALYTICS)),

    FIFTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PRESENT_AND_FUTURE,
            SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_PUBLISH_SHIFTS, SCHEDULE_OVERTIME_WORK,
            ORG_UNIT_EMPLOYEE_PERSONALISATION,
            ANALYTIC_VIEW, ANALYTIC_EDIT, ANALYTIC_PUBLISH_KPI,
            REPORT_VIEW, REPORT_COUNT_BY_ROSTER,
            BULK_CALCULATION_VIEW, BULK_CALCULATION_SHIFTS,
            DESKTOP_LOYALTY,
            PermissionType.POSITION_GROUPS_VIEW), "5_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD,
            RolesSections.BATCH_CALCULATION, RolesSections.REPORTS, RolesSections.ANALYTICS)),

    SIXTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PAST,
            SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_EXPORT, ROSTER_UPLOAD_XLS,
            ANALYTIC_VIEW, ANALYTIC_EDIT, ANALYTIC_CALCULATE_FTE,
            REPORT_VIEW, REPORT_ROSTER_PUBLISH_STATE,
            BULK_CALCULATION_VIEW, BULK_CALCULATION_PLAN_COUNT,
            DESKTOP_EMPLOYEE_TIME,
            PermissionType.POSITION_GROUPS_VIEW), "6_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD,
            RolesSections.BATCH_CALCULATION, RolesSections.REPORTS, RolesSections.ANALYTICS)),

    SEVENTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_POSITION_DISMISS_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE, ORG_UNIT_EMPLOYEE_PERSONALISATION,
            SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_MANAGE_REQUESTS,
            ANALYTIC_VIEW, ANALYTIC_EDIT, ANALYTIC_PUBLISH_FTE,
            REPORT_VIEW, REPORT_HISTORY_DATA_QUALITY,
            DESKTOP_ACCURACY_KPI_FORECAST,
            PermissionType.POSITION_GROUPS_VIEW), "7_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD,
            RolesSections.REPORTS, RolesSections.ANALYTICS)),

    EIGHTH(Arrays.asList(SCHEDULE_VIEW, SCHEDULE_EDIT, ORG_UNIT_EMPLOYEE_PERSONALISATION, ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_POSITION_DISMISS_IN_PAST,
            ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PAST,
            REPORT_VIEW, REPORT_DAY_OFF_QUOTES,
            PermissionType.POSITION_GROUPS_VIEW), "8_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.REPORTS)),

    NINTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE,
            REPORT_VIEW, REPORT_ANALYSE_AVERAGE_CONVERSION), "9_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.REPORTS)),

    TENTH(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PAST,
            REPORT_VIEW, REPORT_PLAN_FACT_CONVERSION), "10_generated", Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.REPORTS)),

    ELEVENTH(Arrays.asList(REPORT_VIEW, REPORT_STAFF_COUNT), "11_generated", Collections.singletonList(RolesSections.REPORTS)),

    TWELFTH(Arrays.asList(REPORT_VIEW, REPORT_TIME_SHEET), "12_generated", Collections.singletonList(RolesSections.REPORTS)),

    THIRTEENTH(Arrays.asList(REPORT_VIEW, REPORT_TARGET_STAFF_COUNT), "13_generated", Collections.singletonList(RolesSections.REPORTS)),

    FOURTEENTH(Arrays.asList(REPORT_VIEW, REPORT_PARAMETERS_VALUES), "14_generated", Collections.singletonList(RolesSections.REPORTS)),

    FIFTEEN(Arrays.asList(ORG_UNIT_EMPLOYEE_PERSONALISATION, ORGANIZATION_UNIT_CREATE, ORG_EMPLOYEE_CREATE, ORG_EMPLOYEE_EDIT,
            ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_CALCULATION_PARTICIPATION_MANAGEMENT, ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PAST, ORGANIZATION_UNIT_POSITION_DISMISS_IN_PRESENT_AND_FUTURE, ORGANIZATION_UNIT_POSITION_DISMISS_IN_PAST,
            ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE, ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PAST, ORGANIZATION_UNIT_NAME_EDIT,
            EMPLOYEE_TABLE_RATE, READ_JOB_TITLES, ORGANIZATION_UNIT_CONTACTS_EDIT, ORG_EMPLOYEE_CONTACT_EDIT_ALL, ORG_EMPLOYEE_CONTACT_EDIT, EDIT_OUTERID,
            ORG_UNIT_EXT_POSITION_EDIT, ORG_EDIT_PASS_PARAMETERS, ORG_EDIT_USER_NAME_PARAMETERS, ORG_EDIT_PERSONAL_PASS_PARAMETERS, ORG_EDIT_PERSONAL_USER_NAME_PARAMETERS, EDIT_EMPLOYEE_TAGS,
            EDIT_ORG_UNIT_TAGS, EDIT_SELF_TAGS), "15_generated", Collections.singletonList(RolesSections.ORG_STRUCTURE)),

    CUSTOM(new ArrayList<>(), "custom__generated", new ArrayList<>()),

    TEST(new ArrayList<>(), "test", new ArrayList<>()),
    SENIOR_MANAGER(Arrays.asList(ORGANIZATION_UNIT_VIEW, ORGANIZATION_UNIT_EDIT, ORGANIZATION_UNIT_POSITION_APPOINTMENT_IN_PRESENT_AND_FUTURE,
            ORGANIZATION_UNIT_POSITION_DISMISS_IN_PRESENT_AND_FUTURE, SCHEDULE_VIEW, SCHEDULE_EDIT, SCHEDULE_CALCULATION_SHIFTS, SCHEDULE_PUBLISH_SHIFTS,
            SCHEDULE_MANAGE_REQUESTS, REPORT_ROSTER_PUBLISH_STATE, MATH_PARAMETERS_VIEW, MATH_PARAMETERS_EDIT, DESKTOP_ACCURACY_KPI_FORECAST,
            NOTIFY_VIEW, ORGANIZATION_UNIT_MANAGER_EDIT, SCHEDULE_DAY_COMMENTS, SCHEDULE_EVENTS, SCHEDULE_VERSION_COMMENTS, ANALYTIC_EDIT,
            ANALYTIC_VIEW, ANALYTIC_CALCULATE_FORECAST, ANALYTIC_CALCULATE_FTE, OTHER_VIEW_PROFILE, OTHER_VIEW_HELP, ORGANIZATION_UNIT_EMPLOYEE_POSITION_END_DATE_CHANGE_IN_PRESENT_AND_FUTURE,
            POSITION_GROUPS_VIEW, ORG_UNIT_SCHEDULE_BLOCK_EDIT, SCHEDULE_CUSTOM_INDICATORS, ORG_UNIT_EMPLOYEE_PERSONALISATION, REPORT_VIEW,
            ORG_EMPLOYEE_EDIT, SCHEDULE_MANAGE_REQUESTS_CREATE, ORG_EMPLOYEE_CREATE, ROSTER_UPLOAD_XLS, ROSTER_UPLOAD_PDF, REPORT_SHIFTS,
            ORG_EDIT_USER_NAME_PARAMETERS, ORG_EDIT_PASS_PARAMETERS, UNIT_OPERATING_MODE, OTHER_WELCOME_PAGE, SYS_LIST_ORG_TYPES_READ,
            EXTERNAL_SUPPORT),
            "Территориальный менеджер",
            Arrays.asList(RolesSections.ORG_STRUCTURE, RolesSections.SCHEDULE_BOARD, RolesSections.REPORTS,
                    RolesSections.MATH_PARAMETERS, RolesSections.FUNCTIONAL_ROLES));

    private List<PermissionType> permissionTypes;
    private String name;
    private final List<RolesSections> sections;
    private List<MathParameter> mathParameters = new ArrayList<>();

    Role(List<PermissionType> permissionTypes, String name, List<RolesSections> sections) {
        this.permissionTypes = permissionTypes;
        this.name = name;
        this.sections = sections;
    }

    public List<PermissionType> getPermissions() {
        return permissionTypes;
    }

    public List<MathParameter> getMathParameters() {
        return mathParameters;
    }

    public String getName() {
        return name;
    }

    public List<String> getNames() {
        return this.getPermissions().stream().map(PermissionType::getTitle).collect(Collectors.toList());
    }

    public List<RolesSections> getRolesSections() {
        return sections;
    }

    public void setPermissionTypes(List<PermissionType> permissionTypes) {
        this.permissionTypes = permissionTypes;
    }

    public void setMathParameters(List<MathParameter> mathParameters) {
        this.mathParameters = mathParameters;
    }

    public void setName(String name) {
        this.name = name;
    }
}

