package wfm.components.calculation;

public enum StrategyList {
    FOT_MINIMIZATION_PRESERVATION_SERVICE_LEVEL,
    IMPROVING_THE_LEVEL_SERVICE_SAVING_FOT,
    MAXIMIZING_CONVERSION_WITH_INCREASED_FOT
}
