{
 "title": "JMeter Dashboard_xxxвап",
 "description": "Monitor your JMeter load test in real time with InfluxDB and Grafana.",
 "tags": [ "load_test" ],
 "time": { "from": "2023-06-22T12:43:21.434Z", "to": "2023-06-22T14:15:53.186Z" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   {
    "name": "application",
    "query": "SHOW TAG VALUES FROM \"belialfff\" WITH KEY = \"application\""
   },
   {
    "name": "transaction",
    "query": "SHOW TAG VALUES FROM \"belialfff\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$application$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all'"
   },
   { "name": "measurement_name", "label": "Measurement name", "query": "${VAR_MEASUREMENT_NAME}" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "${VAR_SEND_INTERVAL}"
   },
   {
    "name": "aggregation",
    "label": "Aggregation time",
    "query": "1s,10s,30s,60s,600s,1800s,3600s"
   }
  ]
 },
 "panels": [
  {
   "title": "Ошибки/пользователи",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "Error %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Error %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"countError\") AS \"error\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Error Rate Avg %",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors per Transaction",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 12, "x": 11, "y": 16 },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT count FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^[<_|>_].*/  ) AND $timeFilter GROUP BY \"transaction\", \"responseCode\",\"responseMessage\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" }
        ],
        [
         { "params": [ "responseMessage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    },
    {
     "title": "Users avg",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "users/m" } },
     "targets": [
      {
       "alias": "Условные_юзеры",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT (sum(\"count\")/99)FROM \"belialfff\" WHERE (\"transaction\" =~ /[<|>].*/  AND (\"statut\" = 'ok' or statut = 'ko') AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Threads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"maxAT\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time(1s) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Метрики запросов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Общая интенсивность запросов по успешности",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "Неуспешные запросы",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "$tag_transaction всего",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND (\"statut\" = 'ok' or statut = 'ko') AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\",  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего запросов",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND (\"statut\" = 'ok' or statut = 'ko') AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Успешные запросы",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND  \"statut\" = 'ok'  AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction неуспешно",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND statut = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\",  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction успешно",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND statut = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\",  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) По всем запросам",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность неуспешных запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction неуспешные",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Неуспешные запросы",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего запросов",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND (\"statut\" = 'ok' or statut = 'ko') AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Неуспешные запросы",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ko' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность успешных запросов",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction успешные",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND \"statut\" = 'ok'  AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Успешные запросы",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего запросов",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /[<|>].*/  AND (\"statut\" = 'ok' or statut = 'ko') AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY  time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Успешные запросы",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем запросам",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем запросам общее",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "avg время ответа запросов",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\"  WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY time(60s) fill(null)  ",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Получено данных по всем запросам (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"rb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Предано данных по всем запросам (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^[<|>].*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Метрики шагов сценариев",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Общая интенсивность шагов сценариев по успешности",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction успешные шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction Неуспешные шаги",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего успешные шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего неуспешные шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction всего шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) По всем шагам сценариев",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность шагов успешных сценариев",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction успешные шаги",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего успешные шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Успешные шаги сценариев",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность шагов неуспешных сценариев",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction Неуспешные шаги",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего неуспешные шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего шаги",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^TC.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Неуспешные шаги сценариев",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ko' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Получено данных по всем шагам сценариев (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"rb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Передано данных по всем шагам сценариев (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем шагам сценариев",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем шагам сценариев общее",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "avg время ответа общее по шагам сценариев",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^TC.*/  ) AND $timeFilter GROUP BY  time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Метрики Сценариев",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Общая интенсивность сценариев по успешности",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction успешные сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction Неуспешные сценарии",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего успешные сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего неуспешные сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "$tag_transaction всего",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) По всем сценариям",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность успешных сценариев",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction успешные сценарии",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего успешные сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ok' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Успешные сценарии",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Интенсивность неуспешных сценариев",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "request/m" } },
     "targets": [
      {
       "alias": "$tag_transaction Неуспешные сценарии",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY \"transaction\" , time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "alias": "Всего неуспешные сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND \"statut\" = 'ko' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "Всего сценарии",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^US.*/  AND (\"statut\" = 'ko' or \"statut\" = 'ok' ) AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null) ",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (95th pct) Неуспешные сценарии",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"statut\" = 'ko' AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем сценариям",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Transactions Response Times (avg) По всем сценариям общее",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "avg время ответа по всем сценариям общее",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok') AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY  time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Пeредано данных по всем сценариям (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Получено данных по всем шагам сценариев (max/m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"rb\") FROM \"$measurement_name\" WHERE ((\"statut\" = 'ko' or \"statut\" = 'ok')  AND \"application\" =~ /^$application$/ AND \"transaction\" =~ /^US.*/  ) AND $timeFilter GROUP BY \"transaction\", time(60s) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}